name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
#    uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2   # original branch
#    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3   # v0.3 zmk branch
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main   # bleeding edge zmk branch